package com.kylin;

import com.kylin.cache.CacheLogic;
import com.kylin.cache.CachePolicy;
import com.kylin.cache.RedisCacheManager;
import com.kylin.datasource.DataSourceRegistry;
import com.kylin.record.SqlExecutionTraceService;
import com.kylin.route.SqlRouteRewriteService;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.sql.*;
import java.util.Map;
import java.util.Properties;
import java.util.concurrent.Executor;

/**
 * 虚拟路由连接层。对外伪装成 Kylin Connection，内部根据 SQL 注解
 * 动态分发到不同数据源。
 */
public class CachedKylinConnection implements Connection {

    private static final Logger log = LoggerFactory.getLogger(CachedKylinConnection.class);

    private final DriverConfig config;
    private final CacheLogic cacheLogic;
    private final CachePolicy cachePolicy;
    private final SqlExecutionTraceService sqlExecutionTraceService;
    private final DataSourceRegistry registry;
    private final SqlRouteRewriteService routeService;

    public CachedKylinConnection(DriverConfig config, RedisCacheManager cacheManager) {
        this(config, cacheManager, new SqlExecutionTraceService(config, cacheManager));
    }

    public CachedKylinConnection(DriverConfig config,
                                 RedisCacheManager cacheManager,
                                 SqlExecutionTraceService sqlExecutionTraceService) {
        this.config = config;
        this.cachePolicy = new CachePolicy(config);
        this.cacheLogic = new CacheLogic(cacheManager, config, cachePolicy);
        this.sqlExecutionTraceService = sqlExecutionTraceService;
        this.registry = config.getDataSourceRegistry();
        this.routeService = new SqlRouteRewriteService(registry, config.isRoutingEnabled());
    }

    public DataSourceRegistry getRegistry() { return registry; }
    public SqlRouteRewriteService getRouteService() { return routeService; }
    DriverConfig getDriverConfig() { return config; }

    // -------------------------------------------------------------------------
    // Statement 工厂方法
    // -------------------------------------------------------------------------

    @Override
    public Statement createStatement() throws SQLException {
        return new CachedKylinStatement(this, cacheLogic, cachePolicy, sqlExecutionTraceService);
    }

    @Override
    public Statement createStatement(int resultSetType, int resultSetConcurrency) throws SQLException {
        return new CachedKylinStatement(this, cacheLogic, cachePolicy, sqlExecutionTraceService, resultSetType, resultSetConcurrency);
    }

    @Override
    public Statement createStatement(int resultSetType, int resultSetConcurrency,
                                     int resultSetHoldability) throws SQLException {
        return new CachedKylinStatement(this, cacheLogic, cachePolicy, sqlExecutionTraceService, resultSetType, resultSetConcurrency, resultSetHoldability);
    }

    @Override
    public PreparedStatement prepareStatement(String sql) throws SQLException {
        return wrapPreparedStatement(sql, SqlCommentParser.safeParse(sql), -1, -1, -1, -1, null, null);
    }

    @Override
    public PreparedStatement prepareStatement(String sql, int resultSetType,
                                              int resultSetConcurrency) throws SQLException {
        return wrapPreparedStatement(sql, SqlCommentParser.safeParse(sql), resultSetType, resultSetConcurrency, -1, -1, null, null);
    }

    @Override
    public PreparedStatement prepareStatement(String sql, int resultSetType,
                                              int resultSetConcurrency,
                                              int resultSetHoldability) throws SQLException {
        return wrapPreparedStatement(sql, SqlCommentParser.safeParse(sql), resultSetType, resultSetConcurrency, resultSetHoldability, -1, null, null);
    }

    @Override
    public PreparedStatement prepareStatement(String sql, int autoGeneratedKeys) throws SQLException {
        return wrapPreparedStatement(sql, SqlCommentParser.safeParse(sql), -1, -1, -1, autoGeneratedKeys, null, null);
    }

    @Override
    public PreparedStatement prepareStatement(String sql, int[] columnIndexes) throws SQLException {
        return wrapPreparedStatement(sql, SqlCommentParser.safeParse(sql), -1, -1, -1, -1, columnIndexes, null);
    }

    @Override
    public PreparedStatement prepareStatement(String sql, String[] columnNames) throws SQLException {
        return wrapPreparedStatement(sql, SqlCommentParser.safeParse(sql), -1, -1, -1, -1, null, columnNames);
    }

    private PreparedStatement wrapPreparedStatement(String originalSql,
                                                    SqlCommentParser.ParsedSql parsed,
                                                    int resultSetType, int resultSetConcurrency, int resultSetHoldability,
                                                    int autoGeneratedKeys, int[] columnIndexes, String[] columnNames) throws SQLException {
        return new CachedKylinPreparedStatement(
                this, cacheLogic, cachePolicy, sqlExecutionTraceService,
                config.isPreparedStatementCacheEnabled(), originalSql, parsed,
                resultSetType, resultSetConcurrency, resultSetHoldability, autoGeneratedKeys, columnIndexes, columnNames);
    }

    // -------------------------------------------------------------------------
    // Connection 委托实现（虚拟连接只读，无事务）
    // -------------------------------------------------------------------------

    @FunctionalInterface
    private interface ConnectionCallback<T> {
        T doInConnection(Connection conn) throws SQLException;
    }

    private <T> T withDefaultConnection(ConnectionCallback<T> callback) throws SQLException {
        try (Connection conn = registry.getConnection(registry.getDefaultDataSourceName())) {
            return callback.doInConnection(conn);
        }
    }

    @Override public void close() throws SQLException { }
    @Override public boolean isClosed() throws SQLException { return false; }
    @Override public DatabaseMetaData getMetaData() throws SQLException { return withDefaultConnection(Connection::getMetaData); }
    @Override public void setAutoCommit(boolean autoCommit) throws SQLException { }
    @Override public boolean getAutoCommit() throws SQLException { return true; }
    @Override public void commit() throws SQLException { }
    @Override public void rollback() throws SQLException { }
    @Override public void rollback(Savepoint savepoint) throws SQLException { }
    @Override public void setReadOnly(boolean readOnly) throws SQLException { }
    @Override public boolean isReadOnly() throws SQLException { return true; }
    @Override public void setCatalog(String catalog) throws SQLException { }
    @Override public String getCatalog() throws SQLException { return withDefaultConnection(Connection::getCatalog); }
    @Override public void setTransactionIsolation(int level) throws SQLException { }
    @Override public int getTransactionIsolation() throws SQLException { return Connection.TRANSACTION_NONE; }
    @Override public SQLWarning getWarnings() throws SQLException { return null; }
    @Override public void clearWarnings() throws SQLException { }
    @Override public CallableStatement prepareCall(String sql) throws SQLException { throw new SQLFeatureNotSupportedException(); }
    @Override public CallableStatement prepareCall(String sql, int resultSetType, int resultSetConcurrency) throws SQLException { throw new SQLFeatureNotSupportedException(); }
    @Override public CallableStatement prepareCall(String sql, int resultSetType, int resultSetConcurrency, int resultSetHoldability) throws SQLException { throw new SQLFeatureNotSupportedException(); }
    @Override public String nativeSQL(String sql) throws SQLException { return sql; }
    @Override public Map<String, Class<?>> getTypeMap() throws SQLException { return withDefaultConnection(Connection::getTypeMap); }
    @Override public void setTypeMap(Map<String, Class<?>> map) throws SQLException { }
    @Override public void setHoldability(int holdability) throws SQLException { }
    @Override public int getHoldability() throws SQLException { return ResultSet.HOLD_CURSORS_OVER_COMMIT; }
    @Override public Savepoint setSavepoint() throws SQLException { throw new SQLFeatureNotSupportedException(); }
    @Override public Savepoint setSavepoint(String name) throws SQLException { throw new SQLFeatureNotSupportedException(); }
    @Override public void releaseSavepoint(Savepoint savepoint) throws SQLException { throw new SQLFeatureNotSupportedException(); }
    @Override public Clob createClob() throws SQLException { return withDefaultConnection(Connection::createClob); }
    @Override public Blob createBlob() throws SQLException { return withDefaultConnection(Connection::createBlob); }
    @Override public NClob createNClob() throws SQLException { return withDefaultConnection(Connection::createNClob); }
    @Override public SQLXML createSQLXML() throws SQLException { return withDefaultConnection(Connection::createSQLXML); }
    @Override public boolean isValid(int timeout) throws SQLException { return true; }
    @Override public void setClientInfo(String name, String value) throws SQLClientInfoException { }
    @Override public void setClientInfo(Properties properties) throws SQLClientInfoException { }
    @Override public String getClientInfo(String name) throws SQLException { return null; }
    @Override public Properties getClientInfo() throws SQLException { return new Properties(); }
    @Override public Array createArrayOf(String typeName, Object[] elements) throws SQLException { return withDefaultConnection(conn -> conn.createArrayOf(typeName, elements)); }
    @Override public Struct createStruct(String typeName, Object[] attributes) throws SQLException { return withDefaultConnection(conn -> conn.createStruct(typeName, attributes)); }
    @Override public void setSchema(String schema) throws SQLException { }
    @Override public String getSchema() throws SQLException { return withDefaultConnection(Connection::getSchema); }
    @Override public void abort(Executor executor) throws SQLException { }
    @Override public void setNetworkTimeout(Executor executor, int milliseconds) throws SQLException { }
    @Override public int getNetworkTimeout() throws SQLException { return 0; }
    @Override public <T> T unwrap(Class<T> iface) throws SQLException { throw new SQLException("Not a wrapper"); }
    @Override public boolean isWrapperFor(Class<?> iface) throws SQLException { return false; }
}
