package com.kylin;

import com.kylin.cache.CacheLogic;
import com.kylin.cache.CachePolicy;
import com.kylin.cache.prepared.PreparedStatementCacheSupport;
import com.kylin.record.SqlExecutionTraceService;
import com.kylin.route.RoutedSql;

import java.io.InputStream;
import java.io.Reader;
import java.net.URL;
import java.sql.*;
import java.util.Calendar;

public class CachedKylinPreparedStatement extends CachedKylinStatement implements PreparedStatement {

    private final String originalSql;
    private final SqlCommentParser.ParsedSql parsed;
    private final RoutedSql routed;
    private final PreparedStatementCacheSupport preparedCacheSupport;
    
    private final int autoGeneratedKeys;
    private final int[] columnIndexes;
    private final String[] columnNames;

    public CachedKylinPreparedStatement(CachedKylinConnection connection,
                                        CacheLogic cacheLogic,
                                        CachePolicy cachePolicy,
                                        SqlExecutionTraceService sqlExecutionTraceService,
                                        boolean preparedStatementCacheEnabled,
                                        String originalSql,
                                        SqlCommentParser.ParsedSql parsed,
                                        int resultSetType, int resultSetConcurrency, int resultSetHoldability,
                                        int autoGeneratedKeys, int[] columnIndexes, String[] columnNames) throws SQLException {
        super(connection, cacheLogic, cachePolicy, sqlExecutionTraceService, resultSetType, resultSetConcurrency, resultSetHoldability);
        this.originalSql = originalSql;
        this.parsed = parsed;
        this.autoGeneratedKeys = autoGeneratedKeys;
        this.columnIndexes = columnIndexes;
        this.columnNames = columnNames;
        
        this.preparedCacheSupport = new PreparedStatementCacheSupport(
                parsed == null ? null : parsed.cleanSql, cachePolicy, preparedStatementCacheEnabled);
        
        // 预执行路由并申请实际连接与 PreparedStatement
        this.routed = connection.getRouteService().routeAndRewrite(originalSql, parsed);
        this.currentActiveConnection = connection.getRegistry().getConnection(routed.datasourceName);
        this.currentActiveStatement = createUnderlyingPreparedStatement();
    }

    protected PreparedStatement createUnderlyingPreparedStatement() throws SQLException {
        if (autoGeneratedKeys != -1) return currentActiveConnection.prepareStatement(routed.executionSql, autoGeneratedKeys);
        if (columnIndexes != null) return currentActiveConnection.prepareStatement(routed.executionSql, columnIndexes);
        if (columnNames != null) return currentActiveConnection.prepareStatement(routed.executionSql, columnNames);
        if (resultSetType != -1 && resultSetConcurrency != -1 && resultSetHoldability != -1) {
            return currentActiveConnection.prepareStatement(routed.executionSql, resultSetType, resultSetConcurrency, resultSetHoldability);
        }
        if (resultSetType != -1 && resultSetConcurrency != -1) {
            return currentActiveConnection.prepareStatement(routed.executionSql, resultSetType, resultSetConcurrency);
        }
        return currentActiveConnection.prepareStatement(routed.executionSql);
    }

    protected PreparedStatement preparedDelegate() {
        return (PreparedStatement) currentActiveStatement;
    }

    @Override
    public ResultSet executeQuery() throws SQLException {
        ensurePreparedQuery("executeQuery");
        boolean useParameterizedCache = shouldUseParameterizedCache();
        String paramFingerprint = preparedCacheSupport.currentFingerprint();
        long startNanos = System.nanoTime();
        try {
            if (!useParameterizedCache) {
                applyProperties(currentActiveStatement);
                ResultSet result = storeCurrentResult(preparedDelegate().executeQuery());
                reportExecution(routed, parsed, paramFingerprint, startNanos, false, null);
                return result;
            }

            applyProperties(currentActiveStatement);
            CacheLogic.CacheExecutionResult result = cacheLogic.executeWithCacheDetailed(
                    parsed, paramFingerprint,
                    preparedDelegate()::executeQuery,
                    routed.datasourceName);
            reportExecution(routed, parsed, paramFingerprint, startNanos, result.cacheHit, null);
            return storeCurrentResult(result.resultSet);
        } catch (SQLException e) {
            reportExecution(routed, parsed, paramFingerprint, startNanos, false, e);
            throw e;
        }
    }

    @Override
    public boolean execute() throws SQLException {
        executeQuery();
        return true;
    }

    @Override
    public ResultSet executeQuery(String sql) throws SQLException {
        throw new SQLException("Cannot call executeQuery(String) on a PreparedStatement");
    }

    @Override
    public boolean execute(String sql) throws SQLException {
        throw new SQLException("Cannot call execute(String) on a PreparedStatement");
    }

    protected boolean shouldUseParameterizedCache() { return preparedCacheSupport.shouldUseCache(); }
    protected void ensurePreparedQuery(String method) throws SQLFeatureNotSupportedException {
        if (!cachePolicy.isQuerySql(parsed.cleanSql)) throw unsupportedSelectOnly(method);
    }
    protected void recordValue(int index, Object value) { preparedCacheSupport.recordValue(index, value); }
    protected void recordObjectValue(int index, Object value) { preparedCacheSupport.recordObjectValue(index, value); }
    protected void markUncacheable(int index) { preparedCacheSupport.markUncacheable(index); }

    @Override public void setNull(int i, int sqlType) throws SQLException { preparedDelegate().setNull(i, sqlType); recordValue(i, null); }
    @Override public void setNull(int i, int sqlType, String typeName) throws SQLException { preparedDelegate().setNull(i, sqlType, typeName); recordValue(i, null); }
    @Override public void setBoolean(int i, boolean x) throws SQLException { preparedDelegate().setBoolean(i, x); recordValue(i, x); }
    @Override public void setByte(int i, byte x) throws SQLException { preparedDelegate().setByte(i, x); recordValue(i, x); }
    @Override public void setShort(int i, short x) throws SQLException { preparedDelegate().setShort(i, x); recordValue(i, x); }
    @Override public void setInt(int i, int x) throws SQLException { preparedDelegate().setInt(i, x); recordValue(i, x); }
    @Override public void setLong(int i, long x) throws SQLException { preparedDelegate().setLong(i, x); recordValue(i, x); }
    @Override public void setFloat(int i, float x) throws SQLException { preparedDelegate().setFloat(i, x); recordValue(i, x); }
    @Override public void setDouble(int i, double x) throws SQLException { preparedDelegate().setDouble(i, x); recordValue(i, x); }
    @Override public void setBigDecimal(int i, java.math.BigDecimal x) throws SQLException { preparedDelegate().setBigDecimal(i, x); recordValue(i, x); }
    @Override public void setString(int i, String x) throws SQLException { preparedDelegate().setString(i, x); recordValue(i, x); }
    @Override public void setBytes(int i, byte[] x) throws SQLException { preparedDelegate().setBytes(i, x); recordValue(i, x); }
    @Override public void setDate(int i, Date x) throws SQLException { preparedDelegate().setDate(i, x); recordValue(i, x); }
    @Override public void setDate(int i, Date x, Calendar cal) throws SQLException { preparedDelegate().setDate(i, x, cal); recordValue(i, x); }
    @Override public void setTime(int i, Time x) throws SQLException { preparedDelegate().setTime(i, x); recordValue(i, x); }
    @Override public void setTime(int i, Time x, Calendar cal) throws SQLException { preparedDelegate().setTime(i, x, cal); recordValue(i, x); }
    @Override public void setTimestamp(int i, Timestamp x) throws SQLException { preparedDelegate().setTimestamp(i, x); recordValue(i, x); }
    @Override public void setTimestamp(int i, Timestamp x, Calendar cal) throws SQLException { preparedDelegate().setTimestamp(i, x, cal); recordValue(i, x); }
    @Override public void setObject(int i, Object x) throws SQLException { preparedDelegate().setObject(i, x); recordObjectValue(i, x); }
    @Override public void setObject(int i, Object x, int targetSqlType) throws SQLException { preparedDelegate().setObject(i, x, targetSqlType); recordObjectValue(i, x); }
    @Override public void setObject(int i, Object x, int targetSqlType, int scaleOrLength) throws SQLException { preparedDelegate().setObject(i, x, targetSqlType, scaleOrLength); recordObjectValue(i, x); }
    @Override public void setURL(int i, URL x) throws SQLException { preparedDelegate().setURL(i, x); recordValue(i, x); }
    @Override public void setNString(int i, String x) throws SQLException { preparedDelegate().setNString(i, x); recordValue(i, x); }
    @Override public void setAsciiStream(int i, InputStream x, int len) throws SQLException { preparedDelegate().setAsciiStream(i, x, len); markUncacheable(i); }
    @Override public void setAsciiStream(int i, InputStream x, long len) throws SQLException { preparedDelegate().setAsciiStream(i, x, len); markUncacheable(i); }
    @Override public void setAsciiStream(int i, InputStream x) throws SQLException { preparedDelegate().setAsciiStream(i, x); markUncacheable(i); }
    @Override public void setUnicodeStream(int i, InputStream x, int len) throws SQLException { preparedDelegate().setUnicodeStream(i, x, len); markUncacheable(i); }
    @Override public void setBinaryStream(int i, InputStream x, int len) throws SQLException { preparedDelegate().setBinaryStream(i, x, len); markUncacheable(i); }
    @Override public void setBinaryStream(int i, InputStream x, long len) throws SQLException { preparedDelegate().setBinaryStream(i, x, len); markUncacheable(i); }
    @Override public void setBinaryStream(int i, InputStream x) throws SQLException { preparedDelegate().setBinaryStream(i, x); markUncacheable(i); }
    @Override public void setCharacterStream(int i, Reader x, int len) throws SQLException { preparedDelegate().setCharacterStream(i, x, len); markUncacheable(i); }
    @Override public void setCharacterStream(int i, Reader x, long len) throws SQLException { preparedDelegate().setCharacterStream(i, x, len); markUncacheable(i); }
    @Override public void setCharacterStream(int i, Reader x) throws SQLException { preparedDelegate().setCharacterStream(i, x); markUncacheable(i); }
    @Override public void setNCharacterStream(int i, Reader x, long len) throws SQLException { preparedDelegate().setNCharacterStream(i, x, len); markUncacheable(i); }
    @Override public void setNCharacterStream(int i, Reader x) throws SQLException { preparedDelegate().setNCharacterStream(i, x); markUncacheable(i); }
    @Override public void setClob(int i, Clob x) throws SQLException { preparedDelegate().setClob(i, x); markUncacheable(i); }
    @Override public void setClob(int i, Reader x, long len) throws SQLException { preparedDelegate().setClob(i, x, len); markUncacheable(i); }
    @Override public void setClob(int i, Reader x) throws SQLException { preparedDelegate().setClob(i, x); markUncacheable(i); }
    @Override public void setBlob(int i, Blob x) throws SQLException { preparedDelegate().setBlob(i, x); markUncacheable(i); }
    @Override public void setBlob(int i, InputStream x, long len) throws SQLException { preparedDelegate().setBlob(i, x, len); markUncacheable(i); }
    @Override public void setBlob(int i, InputStream x) throws SQLException { preparedDelegate().setBlob(i, x); markUncacheable(i); }
    @Override public void setNClob(int i, NClob x) throws SQLException { preparedDelegate().setNClob(i, x); markUncacheable(i); }
    @Override public void setNClob(int i, Reader x, long len) throws SQLException { preparedDelegate().setNClob(i, x, len); markUncacheable(i); }
    @Override public void setNClob(int i, Reader x) throws SQLException { preparedDelegate().setNClob(i, x); markUncacheable(i); }
    @Override public void setRef(int i, Ref x) throws SQLException { preparedDelegate().setRef(i, x); markUncacheable(i); }
    @Override public void setArray(int i, Array x) throws SQLException { preparedDelegate().setArray(i, x); markUncacheable(i); }
    @Override public void setSQLXML(int i, SQLXML x) throws SQLException { preparedDelegate().setSQLXML(i, x); markUncacheable(i); }
    @Override public void setRowId(int i, RowId x) throws SQLException { preparedDelegate().setRowId(i, x); markUncacheable(i); }
    @Override public void clearParameters() throws SQLException { preparedDelegate().clearParameters(); preparedCacheSupport.clear(); }

    @Override public int executeUpdate() throws SQLException { throw unsupportedSelectOnly("executeUpdate"); }
    @Override public void addBatch() throws SQLException { throw unsupportedSelectOnly("addBatch"); }
    @Override public ResultSetMetaData getMetaData() throws SQLException { return preparedDelegate().getMetaData(); }
    @Override public ParameterMetaData getParameterMetaData() throws SQLException { return preparedDelegate().getParameterMetaData(); }
}
